# -------------------------------------------------------------------
# .bash_profile
#
# This file is executed for all interactive shells, i.e., ones you
# log into directly. It may be that some console applications
# (Terminal) execute this for all new tabs or instances.
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# Variable assignments
# -------------------------------------------------------------------
export EDITOR=vim
#export PIP_REQUIRE_VIRTUALENV=true
export PIP_REQUIRE_VIRTUALENV=false
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
export OPSCODE_USER=citrix_jay

# ------------------------------------------------------------------
# Virtual Env Wrapper
# ------------------------------------------------------------------
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
    source /usr/local/bin/virtualenvwrapper.sh
else
    echo "WARNING: Can't find virtualenvwrapper.sh"
fi

# -------------------------------------------------------------------
# PATH building
# -------------------------------------------------------------------

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin

# Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Path to bin directory in HOME
PATH=$PATH:$HOME/bin

# -------------------------------------------------------------------
# Create custom terminal prompt
# -------------------------------------------------------------------
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\[\e[31m\]\H \[\e[33m\]\w\[\e[0m\]\n$\[\033]0;\u@\H:\w\007\] '
# export PS1='\[\e[01;30m\]\t`if [ $? = 0 ]; then echo "\[\e[32m\] ✔ "; else echo "\[\e[31m\] ✘ "; fi`\[\e[00;37m\]\u@\h\[\e[01;37m\]:`[[ $(git status 2> /dev/null | head -n2 | tail -n1) != "# Changes to be committed:" ]] && echo "\[\e[31m\]" || echo "\[\e[33m\]"``[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] || echo "\[\e[32m\]"`$(__git_ps1 "(%s)\[\e[00m\]")\[\e[01;34m\]\w\[\e[00m\]\$ '

# -------------------------------------------------------------------
# Source bash_aliases file
# -------------------------------------------------------------------
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# -------------------------------------------------------------------
# Source bash_functions file
# -------------------------------------------------------------------
if [ -f ~/.bash_functions ]; then
	source ~/.bash_functions
fi

# -------------------------------------------------------------------
# Source global definitions file
# -------------------------------------------------------------------
if [ -f /etc/bashrc ]; then
	source /etc/bashrc
fi

# -------------------------------------------------------------------
# Source git-completion script
# -------------------------------------------------------------------
if [ -f ~/.git-completion.bash ]; then
	source ~/.git-completion.sh
fi

# -------------------------------------------------------------------
# Source git-prompt script
# -------------------------------------------------------------------
if [ -f ~/.git-prompt.sh ]; then
	source ~/.git-prompt.sh
fi

# -------------------------------------------------------------------
# Source .profile script
# -------------------------------------------------------------------
if [ -f ~/.profile ]; then
        source ~/.profile
fi

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# -------------------------------------------------------------------
# AWS CLI 
# -------------------------------------------------------------------
complete -C '/usr/local/bin/aws_completer' aws
export PATH=/usr/local/aws/bin:$PATH
