#!bash
#
# Custom Command-line Fu Function
function cmdfu(){
    curl "http://www.commandlinefu.com/commands/matching/$@/$(echo -n $@ | openssl base64)/plaintext" | less
}
#
# Check URL Certificate
function checkcert(){
    # This function could use some tweaking. jclark - 10/6/2013
    echo | openssl s_client -connect $1:443 2>/dev/null | openssl x509 -dates -noout
}
#
# Powerline shell prompt
function _update_ps1() {
    export PS1="$(~/powerline-shell.py $? 2> /dev/null)"
}

export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"